#
# Module manifest for module 'Whiskey'
#
# Generated by: ajensen
#
# Generated on: 12/8/2016
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Whiskey.psm1'

    # Version number of this module.
    ModuleVersion = '0.31.0'

    # ID used to uniquely identify this module
    GUID = '93bd40f1-dee5-45f7-ba98-cb38b7f5b897'

    # Author of this module
    Author = 'WebMD Health Services'

    # Company or vendor of this module
    CompanyName = 'WebMD Health Services'

    # Copyright statement for this module
    Copyright = '(c) 2016 WebMD Health Services. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Continuous Integration/Continuous Delivery module.'

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @( 'bin\SemanticVersion.dll', 'bin\Whiskey.dll', 'bin\YamlDotNet.dll' )

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    #ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @(
                            'Formats\Whiskey.BuildInfo.format.ps1xml',
                            'Formats\Whiskey.BuildVersion.format.ps1xml',
                            'Formats\Whiskey.Context.format.ps1xml'
                        )

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
                        'BitbucketServerAutomation',
                        'BuildMasterAutomation',
                        'PackageManagement',
                        'PowerShellGet',
                        'ProGetAutomation',
                        'VSSetup'
                     )

    # Functions to export from this module
    FunctionsToExport = @(
                            'Add-WhiskeyApiKey',
                            'Add-WhiskeyCredential',
                            'Add-WhiskeyTaskDefault',
                            'Add-WhiskeyVariable',
                            'Assert-WhiskeyNodePath',
                            'Assert-WhiskeyNodeModulePath',
                            'ConvertFrom-WhiskeyYamlScalar',
                            'ConvertTo-WhiskeySemanticVersion',
                            'Get-WhiskeyApiKey',
                            'Get-WhiskeyTask',
                            'Get-WhiskeyCredential',
                            'Install-WhiskeyTool',
                            'Invoke-WhiskeyNodeTask',
                            'Invoke-WhiskeyNpmCommand',
                            'Invoke-WhiskeyPipeline',
                            'Invoke-WhiskeyBuild',
                            'Invoke-WhiskeyTask',
                            'New-WhiskeyContext',
                            'Publish-WhiskeyBuildMasterPackage',
                            'Publish-WhiskeyNuGetPackage',
                            'Publish-WhiskeyProGetUniversalPackage',
                            'Publish-WhiskeyBBServerTag',
                            'Register-WhiskeyEvent',
                            'Resolve-WhiskeyNuGetPackageVersion',
                            'Resolve-WhiskeyPowerShellModule',
                            'Resolve-WhiskeyTaskPath',
                            'Resolve-WhiskeyVariable',
                            'Set-WhiskeyBuildStatus',
                            'Stop-WhiskeyTask',
                            'Uninstall-WhiskeyTool',
                            'Unregister-WhiskeyEvent'
                         );

    # Cmdlets to export from this module
    CmdletsToExport = @( )

    # Variables to export from this module
    #VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @( 'build', 'pipeline', 'devops', 'ci', 'cd', 'continuous-integration', 'continuous-delivery', 'continuous-deploy' )

            # A URL to the license for this module.
            LicenseUri = 'https://www.apache.org/licenses/LICENSE-2.0'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/webmd-health-services/Whiskey'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
* Added `WHISKEY_BUILD_STARTED_AT` variable. It's a `[datetime]` object that is the date/time the build started.
* Fixed: Whiskey fails builds if a version of Visual Studio 2017 is installed that doesn't have a MSBuild.
* Created `Version` task to replace the `Version`, `VersionFrom`, and `PrereleaseMap` whiskey.yml properties.
* Fixed: when a build that has an Exec task runs in a background job, the build immediately stops after the Exec task executes the process.
* ***BREAKING CHANGE***: We've removed the `Version`, `VersionFrom`, and `PrereleaseMap` properties from whiskey.yml. Use the new `Version` task instead (see the "Upgrade Instructions" below).
* ***BREAKING CHANGE***: Whiskey no longer automatically adds build metadata to your version. Use the new `Version` task to set your build metadata (see the "Upgrade Instructions" below).
* ***BREAKING CHANGE***: Whiskey's default version number is now '0.0.0'. Use the new `Version` task to customize your version number (see the "Upgrade Instructions" below).

## Upgrade Instructions

### Removing `Version` and `PrereleaseMap` Properties

To migrate your `Version` and/or `PrereleaseMap` properties, create a `Version` task as the first task in your pipeline. If your whiskey.yml file looks like this:

    Version: 1.2.3

    PrereleaseMap:
    - feature/*: alpha.$(WHISKEY_BUILD_NUMBER)

    BuildTasks:
    - Pester:
        Path: Tests\*.Tests.ps1

your new whiskey.yml file should look like this:

    BuildTasks:
    - Version:
        Version: 1.2.3
        Prerelease:
        - feature/*: alpha.$(WHISKEY_BUILD_NUMBER)
    - Pester:
        Path: Tests\*.Tests.ps1

### Removing `VersionFrom` Property

If you use the `VersionFrom` property, change your whiskey.yml file from this:

    VersionFrom: Whiskey\Whiskey.psd1

    BuildTasks:
    - Pester:
        Path: Tests\*.Tests.ps1

to this:

    BuildTasks:
    - Version:
        Path: Whiskey\Whiskey.psd1
    - Pester:
        Path: Tests\*.Tests.ps1

### Preserving Default Version Number

To preserve Whiskey's default version numbering, add a Version task to your build pipeline that looks like this:

    BuildTasks:
    - Version: 
        Version: $(WHISKEY_BUILD_STARTED_AT.ToString('yyyy.Mdd')).$(WHISKEY_BUILD_NUMBER)

### Preserving Build Metadata

To preserve Whiskey's old default build metadata, add a Version task to your build pipeline whose "Build" property looks like this:

    BuildTasks:
    - Version:
        Version: 1.2.3
        Build: $(WHISKEY_SCM_BRANCH).$(WHISKEY_SCM_COMMIT_ID.Substring(0,7))

'@
        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
